version: "3"

services:
 mysql:
  image: 'postgres:latest'
    # By default, a Postgres database is running on the 5432 port.
    # If we want to access the database from our computer (outside the container),
    # we must share the port with our computer's port.
    # The syntax is [port we want on our machine]:[port we want to retrieve in the container]
    # Note: You are free to change your computer's port,
    # but take into consideration that it will change the way
    # you are connecting to your database.
  ports:
    - 5432:5432

  environment:
    POSTGRES_USER: $MONGO_USER  # The PostgreSQL user (useful to connect to the database)
    POSTGRES_PASSWORD: $MONGO_PASS  # The PostgreSQL password (useful to connect to the database)
    POSTGRES_DB: $MONGODB_DATABASE_NAME # The PostgreSQL default database (automatically created at first launch)
  volumes:
   - db:/data/db
 app:
  depends_on: 
   - mysql
  build: ./app
  restart: always
  env_file: ./.env
  ports:
   - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
  environment:
   - DB_HOST=mysql
   - DB_USER=postgres
   - DB_PASS=$MONGO_PASS
   - DB_NAME=$MONGODB_DATABASE_NAME

volumes:
 db:
