version: '3.1'

services:
 mysql:
  image: 'postgres:latest'
    # By default, a Postgres database is running on the 5432 port.
    # If we want to access the database from our computer (outside the container),
    # we must share the port with our computer's port.
    # The syntax is [port we want on our machine]:[port we want to retrieve in the container]
    # Note: You are free to change your computer's port,
    # but take into consideration that it will change the way
    # you are connecting to your database.
  ports:
    - 5432:5432
  env_file: ../../.env
  restart: always
  environment:
    - POSTGRES_USER=root  # The PostgreSQL user (useful to connect to the database)
    - POSTGRES_PASSWORD=password  # The PostgreSQL password (useful to connect to the database)
  volumes:
   - mysql-data:/var/lib/postgresql/data
volumes:
 mysql-data:
